### ISSUE TITLE
I got this error while running node server.js from console 

### ISSUE THREAD

**Issue by srizzler** [scotch-io/node-todo#4]
All necessary modules mentioned in package.json are in place. Please help me out.

![err](https://cloud.githubusercontent.com/assets/5557421/4173875/30d5e4ee-356a-11e4-99c8-ac649df01c2c.png)

**Comment by JasterTDC** [comment]
Yo are using an occupied port, check the config and change the port.

**Comment by jasonwr** [comment]
Yes the port 8080 is not associated with the database but is your app port. You need to either kill the port (process tied to it) or set a new port such as 8081 in your server.js

**Comment by NedyUdombat** [comment]
I keep having this error anytime I run the 'node server.js' command

AKAN@user MINGW64 /c/Ampps/www/Code Mentorship/Bears-Project (develop)
$ node server.js
C:\Ampps\www\Code Mentorship\Bears-Project\node_modules\express\lib\express.js:1

(function (exports, require, module, __filename, __dirname) {


SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Ampps\www\Code Mentorship\Bears-Project\node_modul
es\express\index.js:4:5)

Please help me out

**Comment by OttoTrezza** [comment]
CLOSE THE POSTAMN!!!
i have this issue, so i read all the fix options up described...and nothing solve my problem...
even i fix the Firewall problem 
((FROM    https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/))
and restart my PC...
WHEN OPEN GIT BASH CONSOLE AND TYPE NPM START.... THE PROBLEM WAS SOLVED...
then I OPEN my VS..every things work well...
then I OPEN POSTMAN.. and make some request... every things work well...
BUT, when i go to make a put (working in my new service, trying to make an update user) and put into the http bar: localhost:3000/usuario

appears that: 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot PUT /usuario</pre>
    </body>
</html>


every thing fine and i check my console and still work fine...

////////////////////////
IN CONSOLE...
//////////////////////
$ npm start

> backend-server@1.0.0 start D:\proyecto\Adminpro-Angular\backend-server
> nodemon app.js

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Express server,Puerto 3000:online
(node:8904) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Base de datos:online

//////////////////////
END IN CONSOLE...
//////////////////////


so i add the id in the http bar..like that:

localhost:3000/usuario/5bc498ebf6b9d20cb0ef5563

AND BOOM... APP CRASH AGAIN!

///////////////////////
IN CONSOLE...
//////////////////////
$ npm start

> backend-server@1.0.0 start D:\proyecto\Adminpro-Angular\backend-server
> nodemon app.js

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Express server,Puerto 3000:online
(node:860) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Base de datos:online
events.js:167
      throw er; // Unhandled 'error' event
      ^

ReferenceError: ususario is not defined
    at Usuario.findById (D:\proyecto\Adminpro-Angular\backend-server\routes\usuario.js:46:9)
    at D:\proyecto\Adminpro-Angular\backend-server\node_modules\mongoose\lib\model.js:4499:16
    at process.nextTick (D:\proyecto\Adminpro-Angular\backend-server\node_modules\mongoose\lib\query.js:2579:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at D:\proyecto\Adminpro-Angular\backend-server\node_modules\mongoose\lib\model.js:4501:13
    at process.nextTick (D:\proyecto\Adminpro-Angular\backend-server\node_modules\mongoose\lib\query.js:2579:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[nodemon] app crashed - waiting for file changes before starting...(*=>)

//////////////////////
END IN CONSOLE...
//////////////////////

SO.. CLOSE THE POSTMAN..
AND npm start AGAIN..

//////////////////////
IN CONSOLE...
//////////////////////
(<=*)[nodemon] app crashed - waiting for file changes before starting...
^C^CTerminate batch job (Y/N)?
Otto@DESKTOP-JO25NDE MINGW64 /d/proyecto/Adminpro-Angular/backend-server (master)
$ npm start

> backend-server@1.0.0 start D:\proyecto\Adminpro-Angular\backend-server
> nodemon app.js

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
Express server,Puerto 3000:online
(node:9356) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Base de datos:online
//////////////////////
END IN CONSOLE...
//////////////////////

JUST DON'T KNOW WHY, BUT SOLVE THE PROBLEM..
I HOPE THAT THIS HELPS YOU LOCATE  FAULTS...

**Comment by ikhlassramadan** [comment]
![1](https://user-images.githubusercontent.com/42959671/50355635-0b846e00-0558-11e9-9c59-269ef4a2cf93.PNG)
 i have the same problem

**Comment by JSONRice** [comment]
@ikhlassramadan that's because server.js isn't in your current directory: **C:\Windows\server.js** The **dir** command will reveal the contents of the directory. See: https://community.sophos.com/kb/en-us/13195

**Comment by ikhlassramadan** [comment]
@jasonwr  so please what should i do briefly ?

**Comment by JSONRice** [comment]
@ikhlassramadan you need to learn how to use the command line for starters. Navigate to your directory with the server.js and then run it with **node** or **nodemon** I can't help you at this point. You should know where your files are especially since you most likely pulled it in with Git you should know where your Git repositories are.

**Comment by ikhlassramadan** [comment]
![4](https://user-images.githubusercontent.com/42959671/50356394-746ce580-055a-11e9-8e9f-3f06a0169cb6.png)
 server.js in my computer ! so where is the prpblem ?

**Comment by JSONRice** [comment]
@ikhlassramadan this is a **PEBCAK** based issue. You can quickly Google that one. Your server.js is in your Downloads directory. Use **chdir**  to navigate there and run that server file through **node** or **nodemon**

**Comment by ikhlassramadan** [comment]
ok , thank you

**Comment by ikhlassramadan** [comment]
> @ikhlassramadan this is a **PEBCAK** based issue. You can quickly Google that one. Your server.js is in your Downloads directory. Use **chdir** to navigate there and run that server file through **node** or **nodemon**

how to run the server.js through node ?

**Comment by JSONRice** [comment]
> > @ikhlassramadan this is a **PEBCAK** based issue. You can quickly Google that one. Your server.js is in your Downloads directory. Use **chdir** to navigate there and run that server file through **node** or **nodemon**
> 
> how to run the server.js through node ?

Read the aforementioned comments above.

**Comment by ikhlassramadan** [comment]
> > > @ikhlassramadan this is a **PEBCAK** based issue. You can quickly Google that one. Your server.js is in your Downloads directory. Use **chdir** to navigate there and run that server file through **node** or **nodemon**
> > 
> > 
> > how to run the server.js through node ?
> 
> Read the aforementioned comments above.

![capture](https://user-images.githubusercontent.com/42959671/50358921-95860400-0563-11e9-8d1e-59c53947978e.PNG)
 i find the file , after run server this error showed

**Comment by ikhlassramadan** [comment]
> > > > @ikhlassramadan this is a **PEBCAK** based issue. You can quickly Google that one. Your server.js is in your Downloads directory. Use **chdir** to navigate there and run that server file through **node** or **nodemon**
> > > 
> > > 
> > > how to run the server.js through node ?
> > 
> > 
> > Read the aforementioned comments above.
> 
> ![capture](https://user-images.githubusercontent.com/42959671/50358921-95860400-0563-11e9-8d1e-59c53947978e.PNG)
> i find the file , after run server this error showed

the last error solved by run 'npm install' then run server.js through node
